### ISSUE TITLE
where is code about the mathematical definitions from the decomposed signals

### ISSUE THREAD

**Issue by veteranfzf** [BUVANEASH/EEG-Motor-Imagery-Classification---ANN#1]
In paper：To avoid this problem, mathematical definitions are extracted
from the decomposed signals. If nth sample of a wavelet decomposed coefficient at level i is assumedas Di (n), then we can define the following features: RMS,MAV,IEEG,VAR,AAC,P.
but I can't find the code

**Comment by BUVANEASH** [comment]
This Notebook code doesn't follow the paper. The output from the CSP filter applied on DWT coeff is fed as an input to the NN. You can see that the order in which the CSP and DWT were applied is swaped. This is just experimental.
